name: Build and Package AzanUI React App as Node.js Server

on:
  push:
    branches: [ "main" ]
    tags: 
        - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Print tag
        
        run: echo "Tag is: ${{ github.ref_name }}"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install --legacy-peer-deps

      - name: Install test dependencies
        run: |
          npm install --save-dev vitest @vitest/ui jsdom @testing-library/react @testing-library/jest-dom @testing-library/dom --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Build React app
        run: npm run build

      - name: Download portable Node runtime
        run: |
          mkdir -p node
          curl -L https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz -o node.tar.xz
          tar -xf node.tar.xz
          mv node-v20.11.1-linux-x64 node

      - name: Prepare Linux package folder
        run: |
          mkdir -p azan-ui-linux/AzanUI
          cp -r dist azan-ui-linux/AzanUI/
          cp -r node azan-ui-linux/AzanUI/
          cp server.js azan-ui-linux/AzanUI/
          cp systemConfig.js azan-ui-linux/AzanUI/
          cp system.json azan-ui-linux/AzanUI/
          cp run-AzanUI.sh azan-ui-linux/AzanUI/
          chmod +x azan-ui-linux/AzanUI/run-AzanUI.sh

      - name: Create Linux tarball
        run: |
          tar -czf azan-ui-linux.tar.gz -C azan-ui-linux .

      - name: Upload Linux PKG as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: azan-ui-linux
          path: azan-ui-linux.tar.gz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: AzanUI ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux PKG to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: azan-ui-linux.tar.gz
